### ISSUE TITLE
Add support for test operation

### ISSUE THREAD

**Issue by madtisa** [carlosingles/json-patch-query#5]
Test patch operation hasn't seem to be supported

Steps to reproduce:
```js
import patch from 'json-patch-query'

const item = { id: 342 }
console.log(patch.apply(item, [{ op: 'test', path: '$.id', value: 2 }]))
```

**Expected behavior:**
Error, since id with such value is missing
**Actual behavior:**
Ignored operation

**Comment by carlosingles** [comment]
thanks for the report, the test operation has been added into the latest version v1.2.0 as per RFC6902
